version: "3.9"

services: 
  product-service:
    depends_on:
      - "db"
    build:
      context: ./product-service
    command: ["/app/wait-for-it.sh", "db:8890", "--", "npm", "start"]
    ports:
      - "8888:3000"
    environment:
      - test=testvalue
      - DATABASE_PASSWORD=complex_password
      - DATABASE_HOST=db
    volumes:
      - type: bind
        source: ./product-service
        target: /app
    networks:
      - products-network
#--------------------------------------------------------------------------
  db:
    build:
      context: ./product-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=complex_password"
      - "MYSQL_DATABASE=Products"
    ports:
      - 8890:3306
    networks:
      - products-network
#--------------------------------------------------------------------------
  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8889:3000"
    volumes:
      - my-volume:/var/lib/data


# in this section we are creating a volume. and then we will map them in our services.
volumes: 
  my-volume:

# in this section we are creating a custom network. and then we will connect all the services to this network
networks:
  products-network:
    